---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/mentors":
    get:
      summary: list mentors
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/registrations":
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/sessions":
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/logout":
    delete:
      summary: logout session
      responses:
        '200':
          description: successful
  "/logged_in":
    get:
      summary: logged_in session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
